### ISSUE TITLE
bug: I can't speak with my friend and i can't give access to my microphone

### ISSUE THREAD

**Issue by SlavaPlayOrig** [revoltchat/revite#1006] opened 2024-10-09 16:16 UTC
### What happened?

I can't speak with my friend and i can't give access to my microphone 

### Branch

Production (app.revolt.chat)

### Commit hash

I can't speak with my friend and i can't give access to my microphone 

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:24
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:24 UTC
Labels: bug
