### ISSUE TITLE
feature request: Transfer Ownership

### ISSUE THREAD

**Issue by expertmanofficial** [revoltchat/revite#822] opened 2022-11-25 09:51 UTC
### What do you want to see?

I want to have Transfer Ownership like in Discord for Revolt servers.

I want to switch the owner of my own Revolt server to another one.

How many times do we need to wait for this feature lol.

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment] 2022-11-25 10:32
That last sentence comes off as a bit rude to me - please remain civil.

Duplicate of revoltchat/backend#196. In the meantime, feel free to [contact Support](mailto:contact@revolt.chat) to request an ownership transfer - please mention the server's ID and the ID of the user you want to transfer ownership to.

**Closed by Rexogamer** 2022-11-25 10:32 UTC
Labels: enhancement
