### ISSUE TITLE
bug: Server roles

### ISSUE THREAD

**Issue by Nedyos** [revoltchat/revite#897] opened 2023-06-12 22:03 UTC
### What happened?

Server roles, not able to overlap (drag them over) one another, same effect on servers

### Branch

Production (app.revolt.chat)

### Commit hash

revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2023-09-18 17:04
Not a bug but a missing feature - closing due to the client rewrite.

**Closed by Rexogamer** 2023-09-18 17:04 UTC
Labels: bug
