### ISSUE TITLE
NSFW channels need to constantly be verified

### ISSUE THREAD

**Issue by steejo29** [revoltchat/revite#272] opened 2021-09-19 23:23 UTC
When clicking out of and then back into any channel marked as NSFW, you must re-verify yourself by ensuring the checkmark is checked and then clicking on 'Enter Channel'. Tested in Microsoft Store app and also confirmed by a user to occur in Firefox web app.

When exiting the desktop application (Microsoft Store), the checkmark will also uncheck itself.

![2021-09-19_19-18-34](https://user-images.githubusercontent.com/13812987/133946112-1f4cd2b1-551e-4bee-83bc-c2c148edb778.gif)

Microsoft Store app version:
> 51f23f5 (master)
> Nightly 1.0.0-vite
> Native: 1.0.0
> API: 0.5.3-alpha.5
> revolt.js: 5.1.0-alpha.0

**Comment by insertish** [comment] 2021-09-23 16:45
The checkmark shouldn't be unchecking itself, but the gate showing up again is intended behavior to prevent accidentally opening a channel like that.

**Comment by KaoNinjaratzu** [comment] 2022-04-14 13:36
I can understand this is intended behavior to prevent users from accidentally opening a channel with risque content, but the assumption is we're all adults when using this software and doing something like this is bad UI and extremely inconvenient. It would be the equivalent of having to input a password every time you wanted to use your own key to enter your own house, something the user would set up for themselves, not something that every house builder would mandate. 

At least have the option in the account settings to disable this feature and allow us to personally take the risk. The largest reason people left Discord for an alternative is for the developers to stop controlling the way we communicate with each other, so literally censoring our own posts kind of goes against that mantra and will encourage us to just find another software to support.

**Comment by Rexogamer** [comment] 2022-04-14 13:39
I fully agree that an option to disable this functionality is the best way forward - we will hopefully discuss this further internally soon and will share any further updates.

**Comment by KaoNinjaratzu** [comment] 2022-04-14 13:47
Thanks, sorry if my critique sounded harsh. I've been working as a UI engineer for 6+ years and things like deliberately preventing users from using the software how they want under fear of them not knowing how to use a computer is a very fast way to turn people away from the software because it insults their intelligence and only exists to waste time. There are a few ways you can set it up to give us the protection you're looking for while still allowing us to do what we want:

Allow us in the account settings to determine if the functionality is strict, moderate, passive or turned off. Strict means it requires confirmation every time (this is how it is now). Moderate will have it remember your settings for that current session. Passive means it remembers the settings for your account globally on a per server basis, and Off means it will never check and always assume you're fine with seeing mature content. 

If you default it to strict for each account, users will have to go into the settings and choose to reduce the restriction level to their taste. This will protect people who need that protection, but allow those who are fine with it to choose to change it to the less restrictive version, which will make everyone happier. If you want, you can also further add the ability to make it so that NSFW channels cannot be accessed period for those who want to block even being able to view NSFW channels (like a Blocked category) that they can choose. Then the user won't be able to give into temptation or curiousity if that account is for a child or a sensitive person. Though beyond that, you as developers don't have to put our safety into your hands that much. We the users are liable for content we share as long as you the developers have the proper protections in place. and having the NSFW warning is perfectly adequate. Just not every time we click it of course. 

Thanks for hearing me out. Hopefully it gets sorted soon.

**Comment by insertish** [comment] 2023-01-24 17:33
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/64.

**Closed** 2023-01-24 17:38 UTC
Labels: bug, improvement, fluff
