### ISSUE TITLE
bug: can't see options context menu on server icon on mobile

### ISSUE THREAD

**Issue by kaname-png** [revoltchat/revite#743] opened 2022-07-24 12:36 UTC
### What happened?

When trying to view a server's context menu by holding down its icon, this triggers the option to move the server's icon in position, but not the action to show the context menu.

It's very annoying because I don't want to move the server icon, I need to see the context menu to eg: mark a server as read.

Currently the action of moving the server icon is activated in 90% of cases, something really annoying.

I attach a sample video of the error:

https://user-images.githubusercontent.com/56084970/180647272-6ccdf4f6-d2a3-4acd-8194-4f9a9122ef63.mp4

### Branch

Production (app.revolt.chat)

### Commit hash

9a70bb0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Pysics** [comment] 2022-07-25 15:33
@kaname-png This issue is a duplicate of #687.

**Closed** 2022-10-03 00:04 UTC
Labels: bug
