### ISSUE TITLE
Bug: Can't change "Voice Settings" Windows 10

### ISSUE THREAD

**Issue by vasilyvaganov** [revoltchat/revite#779] opened 2022-09-09 11:23 UTC
When I click on "Grant Permission" and select the equipment I want, everything seems to work fine. In fact, after successfully setting up the "Voice Settings" menu and switching to another item - everything resets to "Grant Permission"
I apologize for the broken English
![image](https://user-images.githubusercontent.com/69606089/189338769-061f52e8-a769-49ab-ba24-1ee8c08158d7.png)

**Comment by Rexogamer** [comment] 2022-09-09 20:00
Duplicate of #662.

**Closed by Rexogamer** 2022-09-09 20:00 UTC
