### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by MrANANAS1** [revoltchat/revite#1043] opened 2024-10-18 20:08 UTC
### What happened?

I downloaded the Revolt app, but when I called a friend, the sound did not turn on, then I went into the settings, put it there, then went out and did not work again, then went back into the settings, put the speaker and microphone out again, did not work, then went back in and I see that it was reset again where the speaker and microphone help solve the problem

### Branch

Production (app.revolt.chat)

### Commit hash

I downloaded the Revolt app, but when I called a friend, the sound did not turn on, then I went into the settings, put it there, then went out and did not work again, then went back into the settings, put the speaker and microphone out again, did not work, then went back in and I see that it was reset again where the speaker and microphone help solve the problem

### Relevant log output

I downloaded the Revolt app, but when I called a friend, the sound did not turn on, then I went into the settings, put it there, then went out and did not work again, then went back into the settings, put the speaker and microphone out again, did not work, then went back in and I see that it was reset again where the speaker and microphone help solve the problem

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:19
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:19 UTC
Labels: bug
