### ISSUE TITLE
Feature request: Integrated GIF and emoji button

### ISSUE THREAD

**Issue by iSaluki** [revoltchat/revite#729] opened 2022-07-09 09:24 UTC
Allow users to send emojis and GIFs via a menu situated somewhere in the message box. Just pull things like GIFs from a public API.

**Comment by LedaThemis** [comment] 2022-07-09 22:17
Partially a duplicate of #290, and the emoji picker was implemented in 6bf58e83790eac2e6adba17057bad2fea71f3c7f, #730

**Comment by Rexogamer** [comment] 2022-07-10 11:14
As an emoji picker has been added, I'm closing this as a duplicate of #290

**Closed by Rexogamer** 2022-07-10 11:14 UTC
