### ISSUE TITLE
bug: Granting Audio Permissions Doesn't Work

### ISSUE THREAD

**Issue by EndLordMC** [revoltchat/revite#848] opened 2023-03-12 03:38 UTC
### What happened?

When visiting the Voice Settings in both the Revolt desktop client, and web app, clicking the "Grant Permission" button only works temporarily. Revolt does use the microphone when in the Voice Settings tab, but as soon as the user leaves the voice settings, Revolt stops using the mic and permissions are reset.

This doesn't appear to be a user permission issue, as i tried using the `chmod` command to change the user permissions accordingly, but nothing changed. I also tried running the program via the console, bu
t there was no meaningful output.

I would really like to use revolt, but how can i recommend this to my friends when a basic feature isn't working? Could this be related to #662 ? That was posted all the way back in June of last year.

[system_info.txt](https://github.com/revoltchat/revite/files/10949922/system_info.txt)

### Branch

Production (app.revolt.chat)

### Commit hash

21175df

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2023-03-12 13:02
Duplicate of #560; closing due to client/voice server rewrite.

**Closed by Rexogamer** 2023-03-12 13:02 UTC
Labels: bug

**Comment by EndLordMC** [comment] 2023-03-14 19:47
May i ask why this has been closed as  "Not planned"? Shouldn't this issue be more of a priority?

**Comment by stationaryStation** [comment] 2023-03-14 19:51
Rexo has already given her answer. The Client and the Voice Server are currently being rewritten, so it will most definitely be fixed there.

**Comment by EndLordMC** [comment] 2023-03-17 15:39
Alright, i understand now. Thanks for the info :)
