### ISSUE TITLE
feature request: 12 hour time override in Appearance settings

### ISSUE THREAD

**Issue by Alex-Sour** [revoltchat/revite#756] opened 2022-08-13 21:31 UTC
### What do you want to see?

My clients are showing 24 hour time, even though I like 12 hour time, and there seems to be no override in settings :(

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment] 2022-08-13 23:42
Duplicate of #470.

**Closed by Rexogamer** 2022-08-13 23:42 UTC
Labels: enhancement
