### ISSUE TITLE
Revolt holds up while switching screens on mobile.

### ISSUE THREAD

**Issue by EnokiUN** [revoltchat/revite#421] opened 2021-11-30 13:31 UTC
## Issue
So when you try to switch channels / servers on the mobile **web** app it holds up for a bit.

### System specifications
Infinix note 7 lite, Android 10 running XOS v6.1.

### Attachments
This little [recording](https://youtu.be/GPzxNL03BBk)

**Comment by Rexogamer** [comment] 2021-12-28 00:21
Just out of curiosity, is this still an issue after some recent updates? I think it might be best to get input from a few more people/confirmation that this remains an issue before declaring this a confirmed bug and such

**Comment by insertish** [comment] 2022-01-05 20:31
This may have been partially fixed in fc91a75acb48c85179c1387d50a05e8377ac390b and 136faadcec04fbfd46823252f266355682b40751 to dbf681c2e909827c42f093bac34f85013bb3aa93.

**Comment by Rexogamer** [comment] 2022-02-20 22:15
Closing due to inactivity - if this is still an issue, feel free to reopen this/a new issue. Thanks!

**Closed by Rexogamer** 2022-02-20 22:15 UTC
Labels: bug, question, pwa
