### ISSUE TITLE
bug: resolution for audio output and input

### ISSUE THREAD

**Issue by Damnedsoul3** [revoltchat/revite#1045] opened 2024-10-18 20:26 UTC
### What happened?

when you give permission to access the microphone and headphones to the application, after closing the settings menu, everything is reset back. I can't adjust the sound because of this

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:19
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:19 UTC
Labels: bug
