### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Asl-script** [revoltchat/revite#853] opened 2023-03-15 21:48 UTC
### What happened?

I was expecting for my account ID to copy. It did not copy when I pressed "Click to copy"

### Branch

Production (app.revolt.chat)

### Commit hash

e17e556 (master)
Nightly 1.0.1
API: 0.5.16
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
I think this is the right thing (sorry if it isnt just comment and ill fix it)

createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError$1 (createError.js:16:15)
    at settle (settle.js:17:12)
    at XMLHttpRequest.Or (xhr.js:66:7)
```

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2023-03-15 21:55
Duplicate of #842.

**Closed by Rexogamer** 2023-03-15 21:55 UTC
Labels: bug
