### ISSUE TITLE
bug: sound doesn't work

### ISSUE THREAD

**Issue by tired-6** [revoltchat/revite#1001] opened 2024-10-09 11:00 UTC
### What happened?

asks for permission to use and resets after exiting settings, I don't know what to do.
![Image](https://github.com/user-attachments/assets/7cad3029-4689-4af2-a221-08e1a8e80fce)
im russian, that's why it's Russian in the screenshot.

### Branch

Production (app.revolt.chat)

### Commit hash

Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by rrhymee** [comment] 2024-10-09 11:29
нажми дать разрешение

**Comment by JackDotJS** [comment] 2024-10-19 10:25
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:25 UTC
Labels: bug
