### ISSUE TITLE
bug: Microphone and sound settings are not saved

### ISSUE THREAD

**Issue by hackhostdev** [revoltchat/revite#986] opened 2024-10-08 11:59 UTC
### What happened?

Microphone and sound settings are not saved

### Branch

Production (app.revolt.chat)

### Commit hash

Microphone and sound settings are not saved

### Relevant log output

Microphone and sound settings are not saved

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [x] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:29
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:29 UTC
Labels: bug
