### ISSUE TITLE
Time overlaps the edited message sign

### ISSUE THREAD

**Issue by tonyG433** [revoltchat/revite#394] opened 2021-11-12 10:30 UTC
Here is a short gif that can explain it all. I am pretty sure that the numbers that cover the (edited) letters is the current time, but i don't know why is it happening. 
![5fmu6iKHr](https://user-images.githubusercontent.com/83699240/141452274-ba9db019-04f1-4663-992c-aa05d911900e.gif)

**Comment by insertish** [comment] 2021-11-14 15:57
Duplicate of #324

**Closed by insertish** 2021-11-14 15:57 UTC
