### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by switchbladekisses999** [revoltchat/revite#1025] opened 2024-10-11 13:58 UTC
### What happened?

I can't give permission to access sounds. I click "Give permission" but just exit the settings or click on other options and it asks for permission again

### Branch

Production (app.revolt.chat)

### Commit hash

Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:17
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:17 UTC
Labels: bug
