### ISSUE TITLE
[Bug Report] unread server/dm icons are greyed out on iOS

### ISSUE THREAD

**Issue by marimoons** [revoltchat/revite#547] opened 2022-02-26 21:28 UTC
On the iOS website servers that have an unread notification and the profile picture are greyed out and almost invisible 

you can ask for more screenshots of other things if you need I am @marimuns on revolt

![E3AF2031-4891-4843-986C-A510A7864B07](https://user-images.githubusercontent.com/100493315/155859631-bdef56cb-33ee-4fe9-8dc7-cd4053f090ce.jpeg)

**Comment by Rexogamer** [comment] 2022-02-27 19:18
Can't reproduce on iPadOS 15.3.1 - what version of iOS are you using?

**Comment by marimoons** [comment] 2022-02-27 21:04
iOS 15.3.1 on an iPhone XS

**Comment by janderedev** [comment] 2022-02-27 21:55
Can't reproduce either - iPhone 11 iOS 15.3

**Comment by insertish** [comment] 2022-04-29 18:44
Closing due to lack of information.

**Closed by insertish** 2022-04-29 18:44 UTC
Labels: bug, pwa
