### ISSUE TITLE
Deleting the channel you have open causes the client to bug

### ISSUE THREAD

**Issue by ThatTonybo** [revoltchat/revite#212] opened 2021-09-08 23:44 UTC
If you delete a channel that is open in your client, you will still see the channel, however the channel list will disappear and you will be unable to change servers or other actions until you reload (Ctrl+R)

**Comment by TaiAurori** [comment] 2021-09-08 23:52
Can confirm this has happened to me multiple times before, but I can't easily cause it to happen on demand. This issue might need additional steps to reproduce it.

**Comment by goaaats** [comment] 2021-09-08 23:55
I fixed this in https://github.com/revoltchat/revite/pull/206

**Comment by insertish** [comment] 2021-09-09 19:53
Seems to be fixed in #206.

**Closed by insertish** 2021-09-09 19:53 UTC
