### ISSUE TITLE
bug: autumn is down again

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#942] opened 2023-09-30 07:42 UTC
### What happened?

please fix the autumn server now, or find an alternative that will not keep shutting down

i have tried everything and nothing is working, and earlier on when i first logged in today i noticed the images were also not loading at all so i think a closed source file uploader should be used instead of crappy open source ones that will just keep shutting down with no reason

please do not reply if you are unhelpful or unkind to me when replying

### Branch

Production (app.revolt.chat)

### Commit hash

![IMG_7009](https://github.com/revoltchat/revite/assets/111091825/c71c4e32-d25a-41ac-9d86-e5029e4cf917)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2023-09-30 08:13
Known issue; closing as not a Revite issue, but we're aware of the issue and will resolve it as soon as possible ^^

**Closed by Rexogamer** 2023-09-30 08:13 UTC
Labels: bug

**Comment by pinkjimrussiagirl** [comment] 2023-09-30 09:49
> Known issue; closing as not a Revite issue, but we're aware of the issue and will resolve it as soon as possible ^^

idk why it keeps shutting down but is there a way of keeping it running or do you know why it keeps shutting down

**Comment by Rexogamer** [comment] 2023-09-30 10:10
We are still investigating the issue.

**Comment by pinkjimrussiagirl** [comment] 2023-09-30 10:19
> We are still investigating the issue.

ok, i hope it’s back up later today so i can send images and files and to be able to change my pfp

**Comment by Rexogamer** [comment] 2023-10-01 12:18
Autumn should now be back up. Regarding your edit, the problem is not Autumn (the software) itself, and proprietary platforms are worse as we cannot inspect or improve them; this issue is with the actual host's hardware. Locking as resolved.
