### ISSUE TITLE
bug: settings are not saved

### ISSUE THREAD

**Issue by StriderStas** [revoltchat/revite#1038] opened 2024-10-17 10:49 UTC
### What happened?

I want to chat with my friend through this app, since Discord has been blocked in the Russian Federation. I am asked to give permission, but after I give permission, the microphone still does not work.
And when you re-enter the settings, they ask for permission again.

### Branch

Production (app.revolt.chat)

### Commit hash

Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:13
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:13 UTC
Labels: bug
