### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Garpe0x** [revoltchat/revite#423] opened 2021-12-04 01:49 UTC
![image](https://user-images.githubusercontent.com/93454632/144692452-d989d479-f4be-46c5-8923-001437de4ec2.png)
when exiting or deleting all the servers it stays on that screen

**Comment by Rexogamer** [comment] 2021-12-21 22:34
Duplicate of #447.

**Closed by Rexogamer** 2021-12-21 22:34 UTC
