### ISSUE TITLE
bug: microphone permission

### ISSUE THREAD

**Issue by delayzee** [revoltchat/revite#1024] opened 2024-10-11 13:30 UTC
### What happened?

In the settings, when asking for permission to use a microphone, pressing the button and exiting the settings, the permission is constantly reset. Use becomes impossible! [Image](https://github.com/user-attachments/assets/0a374f9c-5f76-41e7-adcf-468237aaa26a)

### Branch

Production (app.revolt.chat)

### Commit hash

Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by delayzee** [comment] 2024-10-11 13:43
How is work progressing in this direction?

**Comment by JackDotJS** [comment] 2024-10-19 10:17
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:17 UTC
Labels: bug
