### ISSUE TITLE
bug: I can't give permission to the microphone and headphones

### ISSUE THREAD

**Issue by pavlin1412** [revoltchat/revite#995] opened 2024-10-09 06:56 UTC
### What happened?

A "give permission" button appears, I click it but nothing happens

### Branch

Nightly (nightly.revolt.chat)

### Commit hash

Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by syorito-hatsuki** [comment] 2024-10-09 12:52
Ye. Same, Flatpak version permissions do not work. AppImage version works but permission drop on every re launch

**Comment by JackDotJS** [comment] 2024-10-19 10:26
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:26 UTC
Labels: bug
