### ISSUE TITLE
Voice Settings bug 

### ISSUE THREAD

**Issue by Logwn** [revoltchat/revite#662] opened 2022-06-05 16:02 UTC
Whenever you click off and back on the voice settings it will always say you need to grant permission even if permission is already granted.

**Comment by I2rys** [comment] 2022-06-08 05:55
I tried to reproduce this and It does not seem to work both on web & desktop.

**Comment by DylanLogan2581** [comment] 2022-07-06 15:53
This issue still exists. Every time I open "Voice Settings" I am prompted to grant permission to access audio settings.

**Comment by henceiusegentoo** [comment] 2022-09-21 13:38
Still is a problem on my device

**Comment by Rexogamer** [comment] 2022-09-21 16:23
Duplicate of #459.

**Closed by Rexogamer** 2022-09-21 16:23 UTC
