### ISSUE TITLE
Settings page persists scroll position

### ISSUE THREAD

**Issue by SpoopyTim** [revoltchat/revite#354] opened 2021-10-23 16:36 UTC
When changing settings, in some sections a scroll bar is available, meaning that you can scroll down to view more settings. However when you change the displayed section, the scroll position persists between pages.

This means that on sections with fewer options and no scroll bar, options may get cut off or not show at all due to the scroll position being lower than the available settings. While you could go back to a longer page and scroll up to manually reset the scroll position, it seems inefficient and undesirable.

**2 Possible Fixes**

- Reset the scroll position on every page

- Include a scroll bar if the position is below the last option on every page, regardless of the number of items

I would have submitted a pr along with this issue but am not very familiar with preact. Anyone is welcome to do so.

**Comment by insertish** [comment] 2021-10-30 19:51
Duplicate of #108.
Resetting the scroll position seems like a reasonable way to do it.

**Closed by insertish** 2021-10-30 19:51 UTC
Labels: bug, duplicate
