### ISSUE TITLE
bug: Microphone is not allowed

### ISSUE THREAD

**Issue by Lerandiell** [revoltchat/revite#1031] opened 2024-10-12 11:37 UTC
### What happened?

Microphone is not allowed The microphone is not allowed in the settings. Everything is checked in the system, I click allow in the program, select the microphone and speakers, but in fact nothing

### Branch

Production (app.revolt.chat)

### Commit hash

.

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:16
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:16 UTC
Labels: bug
