### ISSUE TITLE
bug: After allowing access to the microphone and camera, access is requested again

### ISSUE THREAD

**Issue by UPCATSjr** [revoltchat/revite#987] opened 2024-10-08 12:40 UTC
### What happened?

After allowing access to the microphone and camera, access is requested again![Image](https://github.com/user-attachments/assets/9701261c-277d-490f-84a4-fa6b89079b41)
![Image](https://github.com/user-attachments/assets/5e77aac2-3dfc-4126-a6d4-fae0fbe2598a)

### Branch

Production (app.revolt.chat)

### Commit hash

[00e6ead](https://github.com/revoltchat/revite/commit/00e6ead9bd6ed84ecc3b8538e9c271102f7353df) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Relevant log output

PC application

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [x] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:29
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:29 UTC
Labels: bug
