### ISSUE TITLE
[Bug Report] First-viewed user list overrides every other server's user list.

### ISSUE THREAD

**Issue by kcseb** [revoltchat/revite#558] opened 2022-03-10 21:53 UTC
### What happened?

When you first open the Revolt Android app, the first server you visit will force that specific server's role hierarchy and member list onto every other server you visit. See videos below for example. 

Case 1) I open Revolt to my own server, view the member list, then view the Revolt Lounge server member list. 
https://drive.google.com/file/d/14Uze38StS97dz2BZqzNU78rnf2d6puGS/view

Case 2) I open Revolt to the Revolt Lounge server, view the member list, then view my own server's member list.
https://drive.google.com/file/d/14dK5IiOgk2ATaFP6aKi3E3zvMw8k5C8D/view

Tested on Android 12, OneUI 4.1. 

### Branch

Production (app.revolt.chat)

### Commit hash

d01b9cae4083d08ec1e071c52dbcabf7593cf74b

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2022-03-12 16:52
Duplicate of #507.

**Closed by Rexogamer** 2022-03-12 16:52 UTC
Labels: bug
