### ISSUE TITLE
bug: I can't give permission for sound

### ISSUE THREAD

**Issue by KUFACH** [revoltchat/revite#1019] opened 2024-10-10 17:23 UTC
### What happened?

I can't give permission for sound

### Branch

Production (app.revolt.chat)

### Commit hash

I can't give permission for sound

### Relevant log output

I can't give permission for sound

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:18
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:18 UTC
Labels: bug
