### ISSUE TITLE
Pressing shift to show message options selects text

### ISSUE THREAD

**Issue by LeviOP** [revoltchat/revite#569] opened 2022-03-26 00:46 UTC
Pressing and holding shift to show all message options results in selected text when hitting a button.

**Holding shift** 
![image](https://user-images.githubusercontent.com/35459268/160217801-a8b16789-c88a-4ab8-98b2-5e3a1829c2bc.png)

**After clicking a button**
![image](https://user-images.githubusercontent.com/35459268/160217843-3f548c5c-229d-4f00-af25-5dbf67a38284.png)

Happening in Firefox on Windows 10 on f9f0d5c (main branch)

**Comment by Rexogamer** [comment] 2022-03-26 18:04
Can reproduce using Revolt Desktop 1.0.3 (Revite f9f0d5c on Nightly), although I'm slightly unsure if this is a bug or not - is this meant to facilitate the "copy selection" function (allowing you to copy the author and timestamp alongside the message's content)?

**Comment by LeviOP** [comment] 2022-03-28 15:42
I'm not clicking the copy selection button, just the three dots. And if it was trying to copy only the message, it wouldn't be selecting seemingly random text from multiple messages above and below. I'm pretty sure this is unintended.

**Comment by LeviOP** [comment] 2022-03-29 00:36
I'm just now noticing that this happens whenever you're holding shift - not just when you're trying to push the buttons on the side. If you press and hold shift then click anywhere on the page, the text is selected.

**Comment by Rexogamer** [comment] 2022-04-04 13:40
I can only get the latter to reproduce after already selecting some text, which would indicate that the second part may be a feature of the browser instead of a bug - the first bit seems like a bug though

**Comment by insertish** [comment] 2023-01-24 17:31
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

**Closed** 2023-01-24 17:32 UTC
Labels: improvement
