### ISSUE TITLE
bug: Server can have just space in name

### ISSUE THREAD

**Issue by CyberL1** [revoltchat/revite#820] opened 2022-11-21 18:08 UTC
### What happened?

You can create a server with just space in the name
![obraz](https://user-images.githubusercontent.com/44707958/203128101-64ebfb4b-9c95-413f-9ff0-35aff4f03d6e.png)
![obraz](https://user-images.githubusercontent.com/44707958/203128143-9e3738ef-33e3-489c-be49-003e04f374d2.png)

### Branch

Production (app.revolt.chat)

### Commit hash

[9be4afe](https://github.com/revoltchat/revite/commit/9be4afe241c56e64944ebde5834569ced7c75334)

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2022-12-01 11:26
Closing as a duplicate of #801.

**Closed by Rexogamer** 2022-12-01 11:26 UTC
Labels: bug
