### ISSUE TITLE
bug: The button *give permission*

### ISSUE THREAD

**Issue by KiChing1000-7** [revoltchat/revite#1027] opened 2024-10-12 07:27 UTC
### What happened?

The button *give permission* does not work where to connect the microphone and headphones. When I click on give permission, after I exit the settings, the permission immediately flies off.

### Branch

Production (app.revolt.chat)

### Commit hash

![Image](https://github.com/user-attachments/assets/8f6938cd-b278-49fd-b6b4-bc4af5ae673c)
![Image](https://github.com/user-attachments/assets/6095d93a-ec13-4bc7-9601-d71d257111b4)

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:16
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:16 UTC
Labels: bug
