### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by blipskip** [revoltchat/revite#847] opened 2023-03-12 03:27 UTC
### What happened?

Every time i try to grant permissions for microphone and restart it doesnt work 

### Branch

Production (app.revolt.chat)

### Commit hash

[21175df](https://github.com/revoltchat/revite/commit/21175dffda992c00c2a56b57755b76069c1e0f43) [(production)](https://github.com/revoltchat/revite/tree/production)
Stable 1.0.1
Native: 1.0.6
API: 0.5.16
revolt.js: 6.0.17

### Desktop

- [X] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2023-03-12 13:04
Duplicate of #459; closing due to client/voice server rewrite.

**Closed by Rexogamer** 2023-03-12 13:04 UTC
Labels: bug
