### ISSUE TITLE
Mobile bug on saved notes

### ISSUE THREAD

**Issue by FocalFossa0997** [revoltchat/revite#690] opened 2022-06-15 06:20 UTC
You can scroll past the leftmost of the screen leaving a blank area where the current member list would display, but since it is the saved notes, nothing appears.
![Screenshot_20220614-231740_Chrome](https://user-images.githubusercontent.com/69269521/173756484-e81c434e-1dc1-4cf5-a82e-8e6b05eee88f.jpg)

**Comment by div2005** [comment] 2022-06-15 20:50
Duplicate of #313

**Closed** 2022-06-15 22:26 UTC
