### ISSUE TITLE
Holding to show right click options doesn't work on iPad

### ISSUE THREAD

**Issue by sirsleon** [revoltchat/revite#244] opened 2021-09-15 02:57 UTC
It selects the text rather than display the Reply, Quote Message, Delete Message etc. pop up.

When I hold a message, it shows the Reply, Quote Message etc options. This works on Android Firefox Revolt and Linux Firefox Revolt. When I do it on iPad Safari Revolt, it selects the text instead.

**Comment by insertish** [comment] 2021-10-09 21:29
Duplicate of #138.

**Closed by insertish** 2021-10-09 21:29 UTC
Labels: duplicate
