### ISSUE TITLE
bug: broken members context menu in DMs (Android PWA)

### ISSUE THREAD

**Issue by LazyMeowyCat** [revoltchat/revite#619] opened 2022-05-10 07:43 UTC
![Screenshot_20220510-144418_Chrome](https://user-images.githubusercontent.com/105273199/167576012-17fb1956-220b-4bfe-87c6-9f506690fe88.jpg)
### What happened?

Maybe there should be no context menu, maybe should, but still...
I just swiped to left in DMs and context menu was empty

### Branch

Production (app.revolt.chat)

### Commit hash

cca97f9

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [X] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment] 2022-06-16 19:13
Duplicate of https://github.com/revoltchat/revite/issues/313

**Closed by insertish** 2022-06-16 19:13 UTC
Labels: bug, pwa
