### ISSUE TITLE
the log in button doesnt work on firefox mobile

### ISSUE THREAD

**Issue by Kuro4clipse** [revoltchat/revite#554] opened 2022-03-08 19:58 UTC

**Comment by Rexogamer** [comment] 2022-03-09 21:48
A few questions:
- Are you using Android or iOS?
- What actually happens? Is there no response, or are you getting an unexpected response (e.g. it reloads but doesn't log you in)?
- What version of Firefox and iOS/Android are you using?

**Comment by Rexogamer** [comment] 2022-03-11 16:17
I'm still slightly confused - does the password field not fill in?

**Comment by Kuro4clipse** [comment] 2022-03-12 14:09
im talking about the email adress,i use the latest firefox version and i run android 11

**Comment by Rexogamer** [comment] 2022-03-12 16:50
I see. Would you be able to explain, in as much detail, what's actually happening? I'm still a little confused as to what the issue is - is it that after auto-filling your info, the button doesn't do anything? Is it that there's an issue with how the email address is being entered/detected?

**Comment by Kuro4clipse** [comment] 2022-03-12 16:52
well when i type my email adress and it suggests automatically my email adress and i fill it in,and after i put a password and press log in it doesnt work,i use gboard

**Comment by Rexogamer** [comment] 2022-03-12 16:54
I see. Does it work when you don't auto-fill anything (i.e. pasting/typing your email and password in manually)?

**Comment by Kuro4clipse** [comment] 2022-03-12 16:55
well im the person who is likely lazy to fill the email and i like to fill something quick

**Comment by Rexogamer** [comment] 2022-03-12 17:11
I think there's been a miscommunication - can you check if it works when you don't auto-fill anything and instead manually enter your details? If it works there, this might be an issue with auto-fill

**Comment by Kuro4clipse** [comment] 2022-03-12 17:12
ok thx

**Comment by insertish** [comment] 2022-04-29 18:50
Very confused about this issue, closing for the time being.
But if there is still an issue, please re-open with reproduction steps and ideally screenshots.

**Closed by insertish** 2022-04-29 18:50 UTC
Labels: bug, question, pwa
