### ISSUE TITLE
bug: [Revolt Desktop] [Revolt Web] In page voice settings dont save choose settings after click on the "Give allow" button

### ISSUE THREAD

**Issue by AYKAVU** [revoltchat/revite#992] opened 2024-10-08 23:20 UTC
### What happened?

**Steps to reproduce:**
1. The user goes to https://app.revolt.chat/ home page
2. The user click on the "Gear" button
3. The user goes to "Voice settings" section
4. The user  click on the "Give allow" button
5. The user choose in drop-down list a microphone device
6. The user choose in drop-down list a audio device
7. The user click on the " Cross (close) " button 

**Expecteb behavor:**
- The selected devices are be saved, and when open the voice settings again, they are saved there

**Actual behavor:**
- The selected devices are not saved.

### Branch

Production (app.revolt.chat)

### Commit hash

**Environment:**
- Prod - https://app.revolt.chat/
- Prod - Desktop app. 
    Version - Native: 1.0.6, Nightly 1.0.1, API: 0.7.14, revolt.js: 6.0.17

I`m download this version in Microsoft store

### What browsers are you seeing the problem on?

Chrome

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by MimikFc7** [comment] 2024-10-11 07:54
Hello, same trouble. Linux, Fedora 39 core 6.10.12-100.fc39.x86_64, Xfce desktop,
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

**Comment by JackDotJS** [comment] 2024-10-19 10:31
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:31 UTC
Labels: bug
