### ISSUE TITLE
Entering Mature channels requires re-confirmation every time

### ISSUE THREAD

**Issue by KaoNinjaratzu** [revoltchat/revite#583] opened 2022-04-14 13:27 UTC
When you enter a mature (18+) channel, you have to re-confirm you're over 18 every time you click on the channel, even if you've already typed in that channel. It should confirm once and remember your affirmation for all channels on a per server basis.

**Comment by Rexogamer** [comment] 2022-04-14 13:29
This is a duplicate of #272 - this is also intended behaviour, but we're considering some sort of alternative.

**Closed by Rexogamer** 2022-04-14 13:29 UTC

**Comment by Furthen64** [comment] 2025-02-11 23:46
Please consider an alternative, this is not great design...
