### ISSUE TITLE
bug: voice chat dosent work

### ISSUE THREAD

**Issue by Quibe222** [revoltchat/revite#990] opened 2024-10-08 23:09 UTC
### What happened?

settings and permissions dont save, voice dont work

### Branch

Production (app.revolt.chat)

### Commit hash

[?](https://github.com/revoltchat/revite/commit/?) [(?)](https://github.com/revoltchat/revite/tree/?)
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:29
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:29 UTC
Labels: bug
