### ISSUE TITLE
bug: microphone don't worked!

### ISSUE THREAD

**Issue by Jopapisya12345** [revoltchat/revite#1018] opened 2024-10-10 17:18 UTC
### What happened?

The microphone on the platform refuses to work, constantly demanding permission, although the system issues permission automatically. When you go to settings, it asks you to grant permission again, but as soon as this happens, you need to exit the tab, as the settings are reset. You can't talk to your friends because of this.

### Branch

Production (app.revolt.chat)

### Commit hash

[?](https://github.com/revoltchat/revite/commit/?) [(?)](https://github.com/revoltchat/revite/tree/?)
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [x] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:18
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:18 UTC
Labels: bug
