### ISSUE TITLE
Uploading Large File bug

### ISSUE THREAD

**Issue by GaMeIsNtOvEr** [revoltchat/revite#549] opened 2022-02-27 13:00 UTC
Found it yesterday
tried to upload a 33 MB File with the .zip extension.
after clicking on cancel button (since you're not able to upload a large file)
I wasn't able to chat until i reloaded the website

**Comment by Rexogamer** [comment] 2022-03-10 18:45
Duplicate of #446.

**Closed by Rexogamer** 2022-03-10 18:45 UTC
