### ISSUE TITLE
Confirmation Email no where to be found

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/revite#380] opened 2021-11-09 21:53 UTC
I tried creating an account and confirmation email is no where to be found. I tried using Gmail and Yahoo as an email but there are no confirmation email sent and it's more than 10mins now and still nada

**Comment by djgaven588** [comment] 2021-11-09 23:30
A few hours after creating an account, I also don't seem to have received such an email. Logging in works, however this seems like either a disabled feature or one not working as intended.

**Comment by insertish** [comment] 2021-11-09 23:37
Having issues sending mail from delta, cause unknown.
Likely related to recent configuration reset, cannot confirm yet.

**Comment by insertish** [comment] 2021-11-09 23:45
I can confirm it's not the configuration.

**Comment by insertish** [comment] 2021-11-10 00:37
Seems to work now, going to mark this to check again later.

**Comment by aeristhy** [comment] 2021-11-26 05:15
@insertish seems like this issue is back, more than 10 minutes and I still didn't receive any confirmation email

**Comment by insertish** [comment] 2021-11-30 14:34
Found the issue, fixed again.
Mail server cert expired. (not my fault!)

**Comment by aeristhy** [comment] 2021-11-30 18:50
OOO Nice

**Comment by Rexogamer** [comment] 2021-12-28 00:22
There hasn't been any activity on this for a while so I'm closing this issue - if this re-emerges, feel free to open a new issue on the Delta repo.

**Closed by Rexogamer** 2021-12-28 00:22 UTC
Labels: bug, question, BLOCKED
