### ISSUE TITLE
bug: Audio settings permision doesn't save

### ISSUE THREAD

**Issue by Semerbl4** [revoltchat/revite#998] opened 2024-10-09 08:12 UTC
### What happened?

Cant use voice, permision doesn't saves or applys![Image](https://github.com/user-attachments/assets/f3bc8ac0-5788-4ac9-a513-67e0ed20c83f)

### Branch

Production (app.revolt.chat)

### Commit hash

1234

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:25
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:25 UTC
Labels: bug
