### ISSUE TITLE
bug: Error in audio resolution

### ISSUE THREAD

**Issue by DeniarFomenko** [revoltchat/revite#1048] opened 2024-10-26 19:30 UTC
### What happened?

Hello, when I give permissions to access the sound settings and then close the window, it is not saved and I have to give permission again, this always happens. Please fix the problem.

### Branch

Production (app.revolt.chat)

### Commit hash

Ilya Fomenko

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-27 15:31
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-27 15:31 UTC
Labels: bug
