### ISSUE TITLE
iOS App Implementation (by adding web app to home screen)

### ISSUE THREAD

**Issue by MrWinterz98** [revoltchat/revite#345] opened 2021-10-18 20:33 UTC
This gives a bit of a feel on what the iOS app may look like and I think we could implement some more support.
I've tried this out and it seems like there are some bugs that you may be able to fix:
- Sending media through the web app that was added to the homescreen does not work (might be a bug from Apple)
> This works on the normal browser.
> This also works with an external mouse, weird.
- Right clicking doesn't exist on mobile (except if you have an external mouse), please refer to issue #343  as well.

Otherwise, the whole experience is okay and could have some work, of course, this is expected because the revolt web app is still being worked on to support mobile and for desktop. The native mobile app is still in testing so we can't expect that to come soon either, so other than the 2 bugs, they're pretty good.

Hit me up if I missed something.

**Comment by nikeedev** [comment] 2021-11-24 16:20
insert doesnt have ios device to test and fix issue up. 

Revolt isnt made for pc only, but pc version is more supported on functions like right-clicking.

> * Sending media through the web app that was added to the homescreen does not work (might be a bug from Apple)

That should be a bug, bu maybe are fixed already(after a month!!). Have you added any other websites to your homescreen? If not, maybe there is a function that may disable "home-screen web apps" from getting access to Files app(or the Photos app then...)

Ask if you got it fixed with media.

**Comment by Rexogamer** [comment] 2022-06-13 09:26
I can't reproduce the first issue at this point (I could previously reproduce it the first time I tried to attach anything during a given session), and the second issue was fixed in 18761e2181be627705ced2eceea4721afc71c3bd. Do you have any other suggestions/have you found any other bugs?

**Comment by MrWinterz98** [comment] 2022-06-15 08:46
I have actually stopped testing Revolt on the web on my iPad because the keyboard and mouse I was using to test this is gone now. However, if you have anything about this discussion, please let me know.

Otherwise, you can close this issue.

**Comment by Rexogamer** [comment] 2022-07-07 22:16
Alrighty - I'll close this out now. Feel free to open a new issue if you have any other suggestions or find any bugs; thanks for the feedback!

**Closed by Rexogamer** 2022-07-07 22:16 UTC
Labels: question, improvement, pwa
