### ISSUE TITLE
bug: the Transparency Effects/Seasonal Theme settings do not persist when restarting the app 

### ISSUE THREAD

**Issue by ge4rsh0t** [revoltchat/revite#537] opened 2022-02-12 13:02 UTC
When I set it to turn off Transparency Effects, please have it ensure that it will stay that way by remembering the setting. I have to turn Transparency Effects off every time I launch Revolt. This happens every time.
![image](https://user-images.githubusercontent.com/50729547/153712460-6e4cb456-9aca-4b39-a5c4-dc69452898ce.png)
![image](https://user-images.githubusercontent.com/50729547/153712488-fade1183-f971-48a2-a1ea-563633d395c6.png)

**Comment by Rexogamer** [comment] 2022-02-19 21:51
Can reproduce - [3632b6b](https://github.com/revoltchat/revite/commit/3632b6b35187696ccd15c0a28ce76a1451db6c68) on Desktop

**Comment by insertish** [comment] 2023-01-24 16:06
Closing due to rewrite, https://github.com/revoltchat/frontend.
State issues like this have been fixed in new client.

**Closed by insertish** 2023-01-24 16:06 UTC
Labels: bug, fluff
