### ISSUE TITLE
bug: When a user is unblocked, the messages from user are still blocked, even after client restart.

### ISSUE THREAD

**Issue by kcseb** [revoltchat/revite#627] opened 2022-05-11 19:14 UTC
### What happened?

When you block a user, their messages are hidden. This works fine. However, when you unblock the user, either via server member list or your own friends section, the users messages are still rendered as blocked, even after full client restart. 

### Branch

Production (app.revolt.chat)

### Commit hash

0e5f64afd68b9922823c623596642162eeac69fd

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by erkinalp** [comment] 2022-05-12 15:46
I am sure it is intended to hide messages from previous periods of blocks, as those messages are still annoying.

**Comment by kcseb** [comment] 2022-05-12 15:48
> I am sure it is intended to hide messages from previous periods of blocks, as those messages are still annoying.

That sounds kind of stupid. If I've unblocked a user, chances are it's to either resume communication or to have the further context of a situation. Having these messages remain blocked should not be happening.

**Comment by Rexogamer** [comment] 2022-05-12 20:53
This has been confirmed internally to be a bug.

**Comment by insertish** [comment] 2023-01-24 17:29
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

**Closed by insertish** 2023-01-24 17:29 UTC
Labels: bug
