### ISSUE TITLE
Error on "Retry send"

### ISSUE THREAD

**Issue by crispy-cat** [revoltchat/revite#722] opened 2022-07-04 18:41 UTC
Client info: 
![image](https://user-images.githubusercontent.com/30805430/177204987-e122205e-d55d-4680-9a06-4be284137d1b.png)

Steps to reproduce:
1. Fail to send a message (NetworkError)
2. Try to Retry send

Error stack:
![image](https://user-images.githubusercontent.com/30805430/177204859-5cc4d135-70ef-4e94-a69b-67e0f1f162c5.png)

**Comment by Rexogamer** [comment] 2022-07-21 21:43
I can't reproduce this when I attempt to resend a message after reconnecting; however, if I try to do so whilst offline get a slightly different error:
https://user-images.githubusercontent.com/42586271/180320244-b86b8275-a7ac-4db4-bdb6-364d6662b1f3.MOV

**Comment by insertish** [comment] 2023-01-24 16:41
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

**Closed by insertish** 2023-01-24 16:41 UTC
