### ISSUE TITLE
bug: microphone doesn't work

### ISSUE THREAD

**Issue by ZIPPI18** [revoltchat/revite#1016] opened 2024-10-10 16:53 UTC
### What happened?

you click “allow microphone access”, but it doesn’t help and when you 
exit the settings everything is reset 

![Image](https://github.com/user-attachments/assets/b38f353f-1945-47c3-8160-5e8cee312d47)
![Image](https://github.com/user-attachments/assets/3ea26b9f-1b42-4197-a534-cf18aba75389)

### Branch

Production (app.revolt.chat)

### Commit hash

I don't know

### Relevant log output

In an application on your computer

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:23
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:23 UTC
Labels: bug
