### ISSUE TITLE
add screen share

### ISSUE THREAD

**Issue by Lil-auxi** [revoltchat/revite#854] opened 2023-03-16 14:11 UTC
### What do you want to see?

hello everyone i would like to tell you that i love your app besides everything in Revolt Chat i will need this particular thing that is adding screen share i would like to watch with my friends.

thank you everyone 

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by Rexogamer** [comment] 2023-04-21 20:46
Closing as a duplicate of revoltchat/vortex#4, which is on hold due to the voice server rewrite.

**Closed by Rexogamer** 2023-04-21 20:46 UTC
Labels: enhancement

**Comment by alexanderjuliao** [comment] 2026-02-10 18:23
PLS!
