### ISSUE TITLE
bug: does not save voice settings

### ISSUE THREAD

**Issue by HouseOptimist** [revoltchat/revite#985] opened 2024-10-08 11:01 UTC
### What happened?

look

### Branch

Production (app.revolt.chat)

### Commit hash

-

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari, Microsoft Edge, Other (please specify in the "What happened" form)

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:28
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:28 UTC
Labels: bug
