### ISSUE TITLE
bug: Can't activate voice (unmute)

### ISSUE THREAD

**Issue by Shadrous** [revoltchat/revite#1010] opened 2024-10-09 22:26 UTC
### What happened?

Revolt won't allow me or my friends to unmute ourselves. It says that we have to give sound permissions, you click on it; and nothing changes. After leaving settings, when you return back to that menu; it will ask for permissions again, so it resets whatever you do.
It also won't show the commit hash. It's just a question mark. These problems occur both on web version and the MS Store client.

### Branch

Production (app.revolt.chat)

### Commit hash

? (?)
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Chrome, Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:23
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:23 UTC
Labels: bug
