### ISSUE TITLE
Messages won't load after re-entering app

### ISSUE THREAD

**Issue by Forzagod58** [revoltchat/revite#781] opened 2022-09-14 21:39 UTC
When putting android phone to sleep and entering the app again, new messages don't load

Bug encountered on an s10+ on android 12

**Comment by FelixKLG** [comment] 2022-09-16 12:31
I can confirm that this bug appears on iOS as well.
The website has to be completely reloaded by either reloading the page or in-case someone used the 'Add to Home Screen' button they'd need to swipe-close the app.

**Comment by insertish** [comment] 2023-01-24 16:07
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

**Closed by insertish** 2023-01-24 16:07 UTC
Labels: bug
