### ISSUE TITLE
Revolt UI goes behind the safe zone on notched iPhones

### ISSUE THREAD

**Issue by byemc** [revoltchat/revite#479] opened 2022-01-03 17:08 UTC
![F3F57453-2825-430E-B6E7-F86C69997A40](https://user-images.githubusercontent.com/77801870/147958537-0b9a580c-ea6c-4ce4-ae79-c4e80e1d99fe.png) 
![A6923029-5E81-49FB-BBC8-593CAA0BFBCA](https://user-images.githubusercontent.com/77801870/147958672-dd49ecc7-664e-4441-8dae-99e810c7fab7.png)

The PWA for Revolt, at least on my iPhone 13 Pro, has some UI elements go over the safe zone (a space around the notch and the home bar..?)

**To reproduce**:
- Get a notched iPhone (definitely the iPhone 13 [Pro])
- Install Revolt as a PWA (app.revolt.chat>Share Sheet>Add to Home Screen)
- Log into revolt. 

It doesn’t stop the buttons being pressed but might trigger Reachability.

**Comment by Rexogamer** [comment] 2022-01-04 13:33
Duplicate of #370.

**Closed by Rexogamer** 2022-01-04 13:33 UTC
