### ISSUE TITLE
bug: you need to provide access to the microphone

### ISSUE THREAD

**Issue by IvanPodkovko** [revoltchat/revite#1042] opened 2024-10-18 18:10 UTC
### What happened?

When I connected my headphones and gave permission to use them in revolt, after I close the window, the settings are not applied and are simply reset and it does not work to connect the device. I apologize if the Anglican curve

### Branch

Production (app.revolt.chat)

### Commit hash

Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [x] Yes, this bug is specific to the PWA.

**Comment by JackDotJS** [comment] 2024-10-19 10:20
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:20 UTC
Labels: bug
