### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by haxerman123** [revoltchat/revite#878] opened 2023-04-23 06:58 UTC
### What happened?

Emoji style doesn't get applied properly. For example changing it to Twemoji still makes the emojis use the Mutant Remix style by Revolt.

### Branch

Production (app.revolt.chat)

### Commit hash

[c426b6c](https://github.com/revoltchat/revite/commit/c426b6c184c6cfc155f456e5db97615cd79f9cf5) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 1.0.1
Native: 1.0.6
API: 0.5.19
revolt.js: 6.0.17

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by Rexogamer** [comment] 2023-04-23 11:57
Duplicate of #827.

**Closed by Rexogamer** 2023-04-23 11:57 UTC
Labels: bug
