### ISSUE TITLE
bug: the problem with voice chat

### ISSUE THREAD

**Issue by awokotsu** [revoltchat/revite#1004] opened 2024-10-09 14:14 UTC
### What happened?

In the voice settings, I cannot allow the application to use speakers and microphone

### Branch

Production (app.revolt.chat)

### Commit hash

/

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Relevant log output

Revolt Desktop

### Desktop

- [x] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by MimikFc7** [comment] 2024-10-11 07:55
Hello, same trouble. Linux, Fedora 39 core 6.10.12-100.fc39.x86_64, Xfce desktop,
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17

**Comment by JackDotJS** [comment] 2024-10-19 10:24
duplicate of #459.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313

**Closed by JackDotJS** 2024-10-19 10:24 UTC
Labels: bug
